// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServicoDeEsterelizacao.Models;

namespace ServicoDeEsterelizacao.Migrations.MaterialDb
{
    [DbContext(typeof(MaterialDbContext))]
    [Migration("20181120123926_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ServicoDeEsterelizacao.Models.Equipamento", b =>
                {
                    b.Property<string>("MaterialcsId");

                    b.Property<int>("CapacidadeMax");

                    b.Property<int>("CapacidadeMin");

                    b.Property<string>("EquipamentoID")
                        .IsRequired();

                    b.Property<string>("Nome");

                    b.Property<int>("Quantidade");

                    b.HasKey("MaterialcsId");

                    b.ToTable("Equipamento");
                });

            modelBuilder.Entity("ServicoDeEsterelizacao.Models.Materialcs", b =>
                {
                    b.Property<string>("MaterialcsId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<int>("Quantidade");

                    b.HasKey("MaterialcsId");

                    b.ToTable("Materialcs");
                });

            modelBuilder.Entity("ServicoDeEsterelizacao.Models.Equipamento", b =>
                {
                    b.HasOne("ServicoDeEsterelizacao.Models.Materialcs", "Material")
                        .WithMany("Equipamentos")
                        .HasForeignKey("MaterialcsId");
                });
#pragma warning restore 612, 618
        }
    }
}
